// Generated by Capy. Entry point — registers the root scene.
import SwiftUI

@main
struct HabitTrackerApp: App {
    var body: some Scene {
        WindowGroup {
            RootView()
        }
    }
}
