// Generated by Capy. House style lives in the library; this file is
// data + composition only. Do not hand-edit — change script.capy.
import React from "react";

type ButtonProps = { children: React.ReactNode; variant: "primary"|"ghost"|"danger"; size: "sm"|"md"|"lg" };

const BUTTON_VARIANT = {
  primary: "bg-indigo-600 hover:bg-indigo-700 text-white",
  ghost:   "bg-transparent hover:bg-slate-100 text-slate-700 border border-slate-200",
  danger:  "bg-red-600 hover:bg-red-700 text-white",
} as const;
const BUTTON_SIZE = { sm: "px-3 py-1 text-sm", md: "px-4 py-2", lg: "px-5 py-3 text-lg" } as const;

const Button: React.FC<ButtonProps> = ({ children, variant, size }) => (
  <button className={`rounded-md font-medium ${BUTTON_VARIANT[variant]} ${BUTTON_SIZE[size]}`}>
    {children}
  </button>
);

const Card: React.FC<{ title: string; children: React.ReactNode }> = ({ title, children }) => (
  <section className="rounded-xl bg-white shadow-sm border border-slate-200 p-6 my-4">
    <h2 className="text-xl font-semibold text-slate-900 mb-4">{title}</h2>
    {children}
  </section>
);

const Field: React.FC<{ label: string; value: string }> = ({ label, value }) => (
  <div className="flex justify-between items-center py-2 border-b border-slate-100 last:border-0">
    <span className="text-slate-500">{label}</span>
    <span className="text-slate-900 font-medium">{value}</span>
  </div>
);

export default function SettingsPage() {
  return (
    <main className="max-w-2xl mx-auto p-8 space-y-3">
      <h1 className="text-3xl font-bold text-slate-900">Settings</h1>
      <Button variant="primary" size="lg">Save changes</Button>
      <Button variant="ghost" size="lg">Discard</Button>
      <Card title={ "Profile" }>
        <Field label="email" value={ "alice@example.com" } />
        <Field label="display" value={ "Alice Chen" } />
        <Field label="timezone" value={ "America/Los_Angeles" } />

      </Card>
      <Card title={ "Danger zone" }>
        <Button variant="danger" size="md">Delete account</Button>

      </Card>


    </main>
  );
}
