// Generated by Capy. Training loop for MNIST classifier.
#include <torch/torch.h>
#include <iostream>
#include "model.h"

constexpr int64_t kBatchSize  = 64;
constexpr int64_t kNumEpochs  = 10;
constexpr double  kLearningRate = 0.001;

int main() {
    torch::manual_seed(0);
    auto device = torch::cuda::is_available() ? torch::kCUDA : torch::kCPU;
    std::cout << "Training on: " << device << std::endl;

    auto train_ds = torch::data::datasets::MNIST("./data")
        .map(torch::data::transforms::Normalize<>(0.1307, 0.3081))
        .map(torch::data::transforms::Stack<>());
    const size_t n_train = train_ds.size().value();
    auto train_loader = torch::data::make_data_loader(
        std::move(train_ds), torch::data::DataLoaderOptions().batch_size(kBatchSize));

    MNISTClassifier model;
    model->to(device);
    torch::optim::Adam optimizer(model->parameters(), kLearningRate);

    for (int64_t epoch = 1; epoch <= kNumEpochs; ++epoch) {
        size_t batch_idx = 0;
        for (auto& batch : *train_loader) {
            auto data = batch.data.to(device);
            auto target = batch.target.to(device);
            optimizer.zero_grad();
            auto output = model->forward(data);
            auto loss = torch::nll_loss(output, target);
            loss.backward();
            optimizer.step();
            if (batch_idx++ % 100 == 0) {
                std::cout << "epoch " << epoch
                          << "  batch " << batch_idx
                          << "  loss " << loss.template item<float>()
                          << std::endl;
            }
        }
        torch::save(model, "checkpoint.pt");
    }
    return 0;
}
