// Generated by Capy.
#pragma once
#include <torch/torch.h>

struct MNISTClassifierImpl : torch::nn::Module {
    MNISTClassifierImpl() {
        l1 = register_module("l1", torch::nn::Conv2d(torch::nn::Conv2dOptions(1, 32, 3)));
        l4 = register_module("l4", torch::nn::Conv2d(torch::nn::Conv2dOptions(32, 64, 3)));
        l8 = register_module("l8", torch::nn::Linear(1600, 128));
        l10 = register_module("l10", torch::nn::Linear(128, 10));
    }

    torch::Tensor forward(torch::Tensor x) {
        x = l1->forward(x);
        x = torch::relu(x);
        x = torch::max_pool2d(x, 2);
        x = l4->forward(x);
        x = torch::relu(x);
        x = torch::max_pool2d(x, 2);
        x = x.flatten(1);
        x = l8->forward(x);
        x = torch::relu(x);
        x = l10->forward(x);
        return torch::log_softmax(x, /*dim=*/1);
    }
    torch::nn::Conv2d l1{nullptr};
    torch::nn::Conv2d l4{nullptr};
    torch::nn::Linear l8{nullptr};
    torch::nn::Linear l10{nullptr};
};
TORCH_MODULE(MNISTClassifier);
