// Generated by Capy. Edit script.capy and re-run to regenerate.
package handlers

import (
    "net/http"
)

// Mount registers every declared handler on the given mux.
func Mount(mux *http.ServeMux) {
    mux.HandleFunc("GET /users", ListUsers)
    mux.HandleFunc("GET /users/{id}", GetUser)
    mux.HandleFunc("POST /users", CreateUser)
    mux.HandleFunc("DELETE /users/{id}", DeleteUser)
}

// GET /users — returns []User
func ListUsers(w http.ResponseWriter, r *http.Request) {
    // TODO: implement ListUsers
    http.Error(w, "ListUsers not implemented", http.StatusNotImplemented)
}

// GET /users/{id} — returns User
func GetUser(w http.ResponseWriter, r *http.Request) {
    // TODO: implement GetUser
    http.Error(w, "GetUser not implemented", http.StatusNotImplemented)
}

// POST /users — accepts UserCreateRequest — returns User
func CreateUser(w http.ResponseWriter, r *http.Request) {
    // TODO: implement CreateUser
    http.Error(w, "CreateUser not implemented", http.StatusNotImplemented)
}

// DELETE /users/{id} — returns void
func DeleteUser(w http.ResponseWriter, r *http.Request) {
    // TODO: implement DeleteUser
    http.Error(w, "DeleteUser not implemented", http.StatusNotImplemented)
}

