// Generated by Capy. Smoke tests verifying every declared route
// is reachable. Replace these with real assertions as you
// implement each handler.
package handlers

import (
    "net/http"
    "net/http/httptest"
    "testing"
)

func Test_ListUsers_RouteRegistered(t *testing.T) {
    mux := http.NewServeMux()
    Mount(mux)
    req := httptest.NewRequest("GET", "/users", nil)
    rr := httptest.NewRecorder()
    mux.ServeHTTP(rr, req)
    // Until the handler body is filled in, this returns 501.
    if rr.Code != http.StatusNotImplemented {
        t.Errorf("expected 501, got %d", rr.Code)
    }
}

func Test_GetUser_RouteRegistered(t *testing.T) {
    mux := http.NewServeMux()
    Mount(mux)
    req := httptest.NewRequest("GET", "/users/{id}", nil)
    rr := httptest.NewRecorder()
    mux.ServeHTTP(rr, req)
    // Until the handler body is filled in, this returns 501.
    if rr.Code != http.StatusNotImplemented {
        t.Errorf("expected 501, got %d", rr.Code)
    }
}

func Test_CreateUser_RouteRegistered(t *testing.T) {
    mux := http.NewServeMux()
    Mount(mux)
    req := httptest.NewRequest("POST", "/users", nil)
    rr := httptest.NewRecorder()
    mux.ServeHTTP(rr, req)
    // Until the handler body is filled in, this returns 501.
    if rr.Code != http.StatusNotImplemented {
        t.Errorf("expected 501, got %d", rr.Code)
    }
}

func Test_DeleteUser_RouteRegistered(t *testing.T) {
    mux := http.NewServeMux()
    Mount(mux)
    req := httptest.NewRequest("DELETE", "/users/{id}", nil)
    rr := httptest.NewRecorder()
    mux.ServeHTTP(rr, req)
    // Until the handler body is filled in, this returns 501.
    if rr.Code != http.StatusNotImplemented {
        t.Errorf("expected 501, got %d", rr.Code)
    }
}

