// Generated by Capy. Implement screen behavior in the *Fragment classes below.
package com.example.habits

import android.os.Bundle
import androidx.appcompat.app.AppCompatActivity
import androidx.fragment.app.Fragment

class MainActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        if (savedInstanceState == null) {
            supportFragmentManager.beginTransaction()
                .replace(R.id.container, HomeFragment())
                .commit()
        }
    }
}


/** Today's habits */
class HomeFragment : Fragment() {
    // Features intended for this screen:
    //   - Daily checklist
    //   - Streak counter
    //   - Reset day
}

/** Past 30 days */
class HistoryFragment : Fragment() {
    // Features intended for this screen:
    //   - Calendar view
    //   - Per-habit stats
}

