// Embed Capy in a Go program to define a tiny HTML DSL inline.
//
// Run: `go run ./examples/embed-html-dsl`
//
// This binary ships its own grammar — there is no `lib.capy` file on
// disk. The library is a Go string literal compiled into the program.
package main

import (
	"fmt"
	"log"

	"github.com/olivierdevelops/capy"
)

const htmlLib = "\n" +
	"extension html\n" +
	"\n" +
	"function page\n" +
	"    arg literal \"page\"\n" +
	"    arg capture title string\n" +
	"    block_closer end\n" +
	"    write `<!DOCTYPE html>\n" +
	"<html>\n" +
	"  <head><title>${title}</title></head>\n" +
	"  <body>\n" +
	"${indent 4 body}\n" +
	"  </body>\n" +
	"</html>\n`\n" +
	"end\n" +
	"\n" +
	"function h1\n" +
	"    arg literal \"h1\"\n" +
	"    arg capture text string\n" +
	"    write `<h1>${text}</h1>\n`\n" +
	"end\n" +
	"\n" +
	"function p\n" +
	"    arg literal \"p\"\n" +
	"    arg capture text string\n" +
	"    write `<p>${text}</p>\n`\n" +
	"end\n" +
	"\n" +
	"function link\n" +
	"    arg literal \"link\"\n" +
	"    arg capture text string\n" +
	"    arg capture href string\n" +
	"    write `<a href=${href}>${text}</a>\n`\n" +
	"end\n" +
	"\n" +
	"function end\n" +
	"end\n"

const source = `
page "Hello from embedded Capy"
    h1 "Welcome!"
    p  "This entire page was generated by a Capy library compiled INTO this Go binary."
    p  "No external lib.capy, no separate capy CLI."
    link "Source" "https://github.com/olivierdevelops/capy"
end
`

func main() {
	lib, err := capy.NewLibrary(htmlLib)
	if err != nil {
		log.Fatalf("compile library: %v", err)
	}

	out, err := lib.Run(source)
	if err != nil {
		log.Fatalf("run: %v", err)
	}

	fmt.Print(out)
}
