// Embed Capy in a Go program to define a tiny HTML DSL inline.
//
// Run: `go run ./examples/embed-html-dsl`
//
// This binary ships its own grammar — there is no `lib.yaml` or `lib.capy`
// file. The library is a Go string literal compiled into the program.
package main

import (
	"fmt"
	"log"

	"github.com/luowensheng/capy"
)

const htmlLib = `
extension html

function page
    arg literal "page"
    arg capture title string
    block_closer end
    template:
        <!DOCTYPE html>
        <html>
          <head><title>{{ .title }}</title></head>
          <body>
        {{ .body | indent 4 }}
          </body>
        </html>
end

function h1
    arg literal "h1"
    arg capture text string
    template_str "<h1>{{ .text }}</h1>\n"
end

function p
    arg literal "p"
    arg capture text string
    template_str "<p>{{ .text }}</p>\n"
end

function link
    arg literal "link"
    arg capture text string
    arg capture href string
    template_str "<a href={{ .href }}>{{ .text }}</a>\n"
end

function end
end
`

const source = `
page "Hello from embedded Capy"
    h1 "Welcome!"
    p  "This entire page was generated by a Capy library compiled INTO this Go binary."
    p  "No external lib.yaml, no separate capy CLI."
    link "Source" "https://github.com/luowensheng/capy"
end
`

func main() {
	lib, err := capy.NewLibrary(htmlLib)
	if err != nil {
		log.Fatalf("compile library: %v", err)
	}

	out, err := lib.Run(source)
	if err != nil {
		log.Fatalf("run: %v", err)
	}

	fmt.Print(out)
}
