<!-- Generated by Capy. House style lives in the library. -->
<script lang="ts">
  import Button from "./Button.svelte";
  import Card   from "./Card.svelte";
  import Field  from "./Field.svelte";
</script>

<main class="max-w-2xl mx-auto p-8 space-y-3">
  <h1 class="text-3xl font-bold text-slate-900">Settings</h1>
  <Button variant="primary" size="lg">Save changes</Button>
  <Button variant="ghost" size="lg">Discard</Button>
  <Card title="Profile">
    <Field label="email" value="alice@example.com" />
    <Field label="display" value="Alice Chen" />
    <Field label="timezone" value="America/Los_Angeles" />

  </Card>
  <Card title="Danger zone">
    <Button variant="danger" size="md">Delete account</Button>

  </Card>


</main>
