package main

import (
	"flag"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// cmdBuild produces a standalone executable that has a library
// baked in. Run the executable against any script and it dispatches
// to the library's commands — no `capy` install required on the
// target host.
//
//	capy build <library> -o <output>
//	capy build recipe -o recipe-tool
//	./recipe-tool run hello.recipe
//	./recipe-tool build hello.recipe
//
// Implementation: writes a tiny main.go that embeds the library
// source as a string constant and dispatches through the
// orchestrator package. Then shells out to `go build`. The user
// needs a Go toolchain installed to run `capy build`; the OUTPUT
// binary has no such requirement.
func cmdBuild(args []string) error {
	// Go's flag package stops at the first positional. Pull flags
	// to the front so `capy build recipe -o tool` works.
	args = reorderFlagsFirst(args)
	fs := flag.NewFlagSet("build", flag.ContinueOnError)
	out := fs.String("o", "", "output binary path (defaults to <lib-name> in cwd)")
	keep := fs.Bool("keep-temp", false, "don't delete the temp build directory after success")
	if err := fs.Parse(args); err != nil {
		return err
	}
	pos := fs.Args()
	if len(pos) != 1 {
		return fmt.Errorf("usage: capy build <library> [-o <output>]")
	}
	libName := pos[0]

	// Resolve the library (by name on CAPY_LIBS, or by direct path).
	var libPath string
	if p, err := resolveLib(libName); err == nil {
		libPath = p
	} else if _, err := os.Stat(libName); err == nil {
		libPath = libName
	} else {
		return fmt.Errorf("library %q not found", libName)
	}

	libSrc, err := os.ReadFile(libPath)
	if err != nil {
		return fmt.Errorf("read library: %v", err)
	}

	// Default output path.
	resolvedName := strings.TrimSuffix(filepath.Base(libPath), filepath.Ext(libPath))
	if *out == "" {
		*out = "./" + resolvedName
	}

	// Materialise a temp Go module that has the lib source embedded.
	tmpDir, err := os.MkdirTemp("", "capy-build-*")
	if err != nil {
		return err
	}
	if !*keep {
		defer os.RemoveAll(tmpDir)
	}

	// Locate the local capy module root so we can use `replace`
	// directives. If we're in the capy source tree, point at it
	// directly; otherwise fall back to `go get` of the published
	// module.
	capyRoot := findCapyModuleRoot()

	mainGoPath := filepath.Join(tmpDir, "main.go")
	if err := os.WriteFile(mainGoPath, []byte(buildMainGo(resolvedName, string(libSrc))), 0644); err != nil {
		return fmt.Errorf("write main.go: %v", err)
	}

	// go.mod with replace pointing at the capy checkout (if found).
	var gomod string
	if capyRoot != "" {
		gomod = fmt.Sprintf(`module capybuild

go 1.22

require github.com/luowensheng/capy v0.0.0
replace github.com/luowensheng/capy => %s
`, capyRoot)
	} else {
		gomod = `module capybuild

go 1.22

require github.com/luowensheng/capy latest
`
	}
	if err := os.WriteFile(filepath.Join(tmpDir, "go.mod"), []byte(gomod), 0644); err != nil {
		return fmt.Errorf("write go.mod: %v", err)
	}
	// If we have a local checkout, copy its go.sum so we don't
	// re-resolve every dep.
	if capyRoot != "" {
		if sumBytes, err := os.ReadFile(filepath.Join(capyRoot, "go.sum")); err == nil {
			_ = os.WriteFile(filepath.Join(tmpDir, "go.sum"), sumBytes, 0644)
		}
	}

	// `go mod tidy` to settle deps for the new module.
	tidy := exec.Command("go", "mod", "tidy")
	tidy.Dir = tmpDir
	tidy.Stdout = os.Stderr
	tidy.Stderr = os.Stderr
	if err := tidy.Run(); err != nil {
		return fmt.Errorf("go mod tidy failed: %v", err)
	}

	// go build.
	absOut, err := filepath.Abs(*out)
	if err != nil {
		return err
	}
	build := exec.Command("go", "build", "-o", absOut, "./...")
	build.Dir = tmpDir
	build.Stdout = os.Stderr
	build.Stderr = os.Stderr
	fmt.Fprintf(os.Stderr, "building %s (this needs the Go toolchain)…\n", resolvedName)
	if err := build.Run(); err != nil {
		return fmt.Errorf("go build failed: %v", err)
	}
	st, _ := os.Stat(absOut)
	size := int64(0)
	if st != nil {
		size = st.Size()
	}
	fmt.Fprintf(os.Stderr, "✓ wrote %s (%.1f MB)\n", *out, float64(size)/1024/1024)
	fmt.Fprintf(os.Stderr, "  try:  %s --help\n", *out)
	return nil
}

// buildMainGo returns the source code of the standalone wrapper
// binary. It embeds the library source as a string constant and
// dispatches to orchestrator.RunCommand for every invocation.
func buildMainGo(libName, libSrc string) string {
	// Build the source line-by-line with concatenation so we don't
	// trip over backticks inside the embedded library source.
	const tmpl = "// Generated by capy build. Do not edit.\n" +
		"package main\n" +
		"\n" +
		"import (\n" +
		"\t\"fmt\"\n" +
		"\t\"os\"\n" +
		"\n" +
		"\t\"github.com/luowensheng/capy/orchestrator\"\n" +
		")\n" +
		"\n" +
		"const libName = %q\n" +
		"\n" +
		"const libSource = %s\n" +
		"\n" +
		"func main() {\n" +
		"\tif len(os.Args) < 2 || os.Args[1] == \"--help\" || os.Args[1] == \"-h\" {\n" +
		"\t\tprintUsage()\n" +
		"\t\treturn\n" +
		"\t}\n" +
		"\t// The library is EMBEDDED in this binary; the user already\n" +
		"\t// trusted it by running the binary. Suppress the\n" +
		"\t// \"not on CAPY_LIBS\" warning that would otherwise fire\n" +
		"\t// for the temp-file path.\n" +
		"\tos.Setenv(\"CAPY_TRUST\", \"1\")\n" +
		"\tf, err := os.CreateTemp(\"\", \"capy-lib-*.capy\")\n" +
		"\tif err != nil { fmt.Fprintln(os.Stderr, err); os.Exit(1) }\n" +
		"\tdefer os.Remove(f.Name())\n" +
		"\tif _, err := f.WriteString(libSource); err != nil { fmt.Fprintln(os.Stderr, err); os.Exit(1) }\n" +
		"\tf.Close()\n" +
		"\n" +
		"\tcmd := os.Args[1]\n" +
		"\targs := os.Args[2:]\n" +
		"\tif err := orchestrator.RunCommand(f.Name(), cmd, args); err != nil { fmt.Fprintln(os.Stderr, err); os.Exit(1) }\n" +
		"}\n" +
		"\n" +
		"func printUsage() {\n" +
		"\tfmt.Printf(\"%%s \\u2014 bundled Capy library (built with capy build)\\n\\n\", libName)\n" +
		"\tfmt.Println(\"USAGE\")\n" +
		"\tfmt.Printf(\"    %%s <command> [args...]\\n\\n\", libName)\n" +
		"\tfmt.Println(\"Try --help for command-specific help.\")\n" +
		"}\n"
	return fmt.Sprintf(tmpl, libName, goRawStringLiteral(libSrc))
}

// goRawStringLiteral encodes s as a Go raw-string literal,
// falling back to a regular interpreted string + escaping if s
// contains a backtick.
func goRawStringLiteral(s string) string {
	if !strings.Contains(s, "`") {
		return "`" + s + "`"
	}
	// Has a backtick — emit as a regular escape-quoted string.
	var b strings.Builder
	b.WriteByte('"')
	for i := 0; i < len(s); i++ {
		c := s[i]
		switch c {
		case '\\':
			b.WriteString(`\\`)
		case '"':
			b.WriteString(`\"`)
		case '\n':
			b.WriteString(`\n`)
		case '\t':
			b.WriteString(`\t`)
		case '\r':
			b.WriteString(`\r`)
		default:
			b.WriteByte(c)
		}
	}
	b.WriteByte('"')
	return b.String()
}

// findCapyModuleRoot looks up from the current working directory
// (and from the capy binary's location) for a go.mod that declares
// `module github.com/luowensheng/capy`. Returns the path, or empty
// when we're not in a checkout.
func findCapyModuleRoot() string {
	candidates := []string{}
	if cwd, err := os.Getwd(); err == nil {
		candidates = append(candidates, cwd)
	}
	if self, err := os.Executable(); err == nil {
		candidates = append(candidates, filepath.Dir(self))
	}
	for _, start := range candidates {
		dir := start
		for i := 0; i < 12; i++ {
			gomod := filepath.Join(dir, "go.mod")
			if data, err := os.ReadFile(gomod); err == nil {
				if strings.Contains(string(data), "module github.com/luowensheng/capy") {
					return dir
				}
			}
			parent := filepath.Dir(dir)
			if parent == dir {
				break
			}
			dir = parent
		}
	}
	return ""
}

// (unused helper — kept here for symmetry with other cmd_* files;
// io.Discard ensures the import is referenced even if all the
// build/copy paths fail at runtime).
var _ = io.Discard
