package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func cmdLib(args []string) error {
	if len(args) == 0 {
		return cmdLibList(nil)
	}
	switch args[0] {
	case "list":
		return cmdLibList(args[1:])
	case "which":
		return cmdLibWhich(args[1:])
	case "new":
		return cmdLibNew(args[1:])
	case "path":
		return cmdLibPath(args[1:])
	default:
		return fmt.Errorf("unknown lib subcommand %q (try: list / which / new / path)", args[0])
	}
}

func cmdLibList(_ []string) error {
	libs := listInstalledLibs()
	if len(libs) == 0 {
		fmt.Println("no libraries found on CAPY_LIBS")
		fmt.Println("search path:")
		for _, p := range libSearchPath() {
			fmt.Println("  ", p)
		}
		return nil
	}
	names := make([]string, 0, len(libs))
	for n := range libs {
		names = append(names, n)
	}
	sort.Strings(names)
	for _, n := range names {
		fmt.Printf("%-20s  %s\n", n, libs[n])
	}
	return nil
}

func cmdLibWhich(args []string) error {
	if len(args) != 1 {
		return fmt.Errorf("usage: capy lib which <name>")
	}
	path, err := resolveLib(args[0])
	if err != nil {
		return err
	}
	fmt.Println(path)
	return nil
}

func cmdLibPath(_ []string) error {
	for _, p := range libSearchPath() {
		fmt.Println(p)
	}
	return nil
}

// cmdLibNew scaffolds a starter library at the first writable
// directory on CAPY_LIBS (creating it if needed).
//
//	capy lib new my-recipe
func cmdLibNew(args []string) error {
	if len(args) < 1 {
		return fmt.Errorf("usage: capy lib new <name>")
	}
	name := args[0]
	// Choose target dir: first entry of CAPY_LIBS that exists or
	// can be created.
	var targetDir string
	for _, p := range libSearchPath() {
		if err := os.MkdirAll(p, 0755); err == nil {
			targetDir = p
			break
		}
	}
	if targetDir == "" {
		return fmt.Errorf("no writable directory on CAPY_LIBS")
	}
	libDir := filepath.Join(targetDir, name)
	if _, err := os.Stat(libDir); err == nil {
		return fmt.Errorf("library %q already exists at %s", name, libDir)
	}
	if err := os.MkdirAll(libDir, 0755); err != nil {
		return err
	}

	// Scaffolded files.
	manifest := fmt.Sprintf(`# Library manifest. See https://luowensheng.github.io/capy/
name        "%s"
version     "0.1.0"
description "A new Capy library."

extension   "txt"

function greet
    arg literal "greet"
    arg capture who string
    write `+"`"+`Hello from %s, ${unquote who}!
`+"`"+`
end

command "run"
    description "Compile and print to stdout."
    let out = (compile context.arg0)
    print out
end

command "compile"
    description "Compile and write to a .txt file."
    let out    = (compile context.arg0)
    let target = "${context.arg0}.txt"
    write_file target out
    print "wrote ${target}"
end
`, name, name)
	readme := fmt.Sprintf(`# %s

A Capy library generated by `+"`capy lib new %s`"+`.

## Try it

`+"```sh"+`
echo 'greet "world"' > hello.%s
capy %s run hello.%s
`+"```"+`

## Customise

Edit `+"`%s.capy`"+`. Add functions, commands, types. Re-run
`+"`capy lib list`"+` to confirm it's picked up.
`, name, name, name, name, name, name)
	example := `greet "world"
`

	if err := os.WriteFile(filepath.Join(libDir, name+".capy"), []byte(manifest), 0644); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(libDir, "README.md"), []byte(readme), 0644); err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Join(libDir, "examples"), 0755); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(libDir, "examples", "hello."+name), []byte(example), 0644); err != nil {
		return err
	}

	fmt.Printf("✓ created library %q at %s\n", name, libDir)
	fmt.Printf("  capy %s run %s/examples/hello.%s\n", name, libDir, name)
	return nil
}

// libraryNameLooksValid returns true when s is plausibly a library
// name (no path separators, no leading dots). Used in dispatch to
// disambiguate `capy <subcommand>` from `capy <lib>`.
func libraryNameLooksValid(s string) bool {
	if s == "" {
		return false
	}
	if strings.HasPrefix(s, ".") || strings.HasPrefix(s, "-") {
		return false
	}
	for _, c := range s {
		if c == '/' || c == '\\' || c == ' ' || c == ':' {
			return false
		}
	}
	return true
}
