<!-- Generated by Capy. House style lives in the library. -->
<script setup lang="ts">
const BUTTON_VARIANT = {
  primary: "bg-indigo-600 hover:bg-indigo-700 text-white",
  ghost:   "bg-transparent hover:bg-slate-100 text-slate-700 border border-slate-200",
  danger:  "bg-red-600 hover:bg-red-700 text-white",
} as const;
const BUTTON_SIZE = { sm: "px-3 py-1 text-sm", md: "px-4 py-2", lg: "px-5 py-3 text-lg" } as const;

type ButtonProps = { variant: keyof typeof BUTTON_VARIANT; size: keyof typeof BUTTON_SIZE };
defineProps<ButtonProps>();
</script>

<template>
  <main class="max-w-2xl mx-auto p-8 space-y-3">
    <h1 class="text-3xl font-bold text-slate-900">Settings</h1>
    <Button variant="primary" size="lg">Save changes</Button>
    <Button variant="ghost" size="lg">Discard</Button>
    <Card title="Profile">
      <Field label="email" value="alice@example.com" />
      <Field label="display" value="Alice Chen" />
      <Field label="timezone" value="America/Los_Angeles" />

    </Card>
    <Card title="Danger zone">
      <Button variant="danger" size="md">Delete account</Button>

    </Card>


  </main>
</template>

<!--
  <Button>, <Card>, <Field> are sibling SFCs in this directory.
  The library guarantees props match the React/Svelte equivalents,
  so the same script.capy compiles to all three frameworks.
-->
