// Generated by Capy from script.capy.
// Habits persist to localStorage keyed by date (YYYY-MM-DD).

const HABITS = [
  { id: "drink_water", label: Drink 8 glasses of water },
  { id: "read", label: Read 20 pages },
  { id: "walk", label: 30 min walk },
  { id: "code", label: Practice coding },
  { id: "meditate", label: Meditate 10 min },
];

const todayKey = () => new Date().toISOString().slice(0, 10);
const storageKey = (k) => `habits:${k}`;

function load(day) {
  try { return JSON.parse(localStorage.getItem(storageKey(day))) || {}; }
  catch { return {}; }
}
function save(day, state) {
  localStorage.setItem(storageKey(day), JSON.stringify(state));
}
function countStreak() {
  let streak = 0;
  const d = new Date();
  while (true) {
    const k = d.toISOString().slice(0, 10);
    const s = load(k);
    const all = HABITS.every((h) => s[h.id]);
    if (!all) break;
    streak++;
    d.setDate(d.getDate() - 1);
  }
  return streak;
}

function render() {
  const day = todayKey();
  const state = load(day);
  document.getElementById("today").textContent = day;
  for (const cb of document.querySelectorAll("input[data-habit]")) {
    cb.checked = !!state[cb.dataset.habit];
  }
  const streak = countStreak();
  document.getElementById("streak").textContent =
    streak > 0 ? `🔥 ${streak}-day streak` : "Start your streak today";
}

document.addEventListener("change", (e) => {
  if (!e.target.matches("input[data-habit]")) return;
  const day = todayKey();
  const state = load(day);
  state[e.target.dataset.habit] = e.target.checked;
  save(day, state);
  render();
});

document.getElementById("reset").addEventListener("click", () => {
  localStorage.removeItem(storageKey(todayKey()));
  render();
});

render();
